// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/google/wire"
	"ongkir-go/app/controller"
	"ongkir-go/app/service"
	"ongkir-go/config"
)

// Injectors from injector.go:

func Initialized(ctx context.Context) *Initialization {
	environment := config.NewEnvironment()
	mongo := config.NewMongo(environment, ctx)
	authService := service.NewAuthService(mongo)
	authController := controller.NewAuthController(authService)
	initialization := NewInitialization(authController)
	return initialization
}

// injector.go:

var authSet = wire.NewSet(controller.NewAuthController, service.NewAuthService)
